### ISSUE TITLE
Added element media:content?

### ISSUE THREAD

**Issue by ssheduardo** [Chouchen/ShikiryuRSS#4]
Hi,
One question, how to added a new method for insert media:content (for mailchimp -> http://kb.mailchimp.com/es/merge-tags/rss-blog/rss-merge-tags)

For example: 

```
<media:content url="http://hathaway.edu/example.jpg" medium="image"> 
<media:content url="http://hathaway.edu/example.jpg" type="image/jpg">
```

Thanks

**Comment by Chouchen** [comment]
`media:content` is part of the MRSS specification which is not supported by this library at the moment (I didn't even know it existed :fearful: )
Now, to help me or anyone wanting to add it : [here](http://www.rssboard.org/media-rss) are the specifications.

**Comment by Chouchen** [comment]
It's done in the new version of this library as of today 🎉
